fix: extend active menu item check url startsWith
pancakeswap/pancake-toolkit pull request #106
Opened 2021-05-17 15:41 UTC by ciruz

I noticed that the active state in the menu is not always correct, so now we also check if the location.pathname starts with the href. Ofc it needs to be than 1, because of ``/``.

Before:

![image](https://user-images.githubusercontent.com/987947/118516107-4e9d9800-b736-11eb-9b44-a2ee632e4c90.png)

![image](https://user-images.githubusercontent.com/987947/118516114-51988880-b736-11eb-8750-d346034a4220.png)

After:

![image](https://user-images.githubusercontent.com/987947/118516358-8573ae00-b736-11eb-9c3b-ab0b7912bd2f.png)

2021-05-20 03:05 UTC, hachiojidev requested changes
Can you please follow our [commit guidelines](https://docs.pancakeswap.finance/code/contributing#committing)

2021-05-20 06:20 UTC, ciruz commented
> Can you please follow our [commit guidelines](https://docs.pancakeswap.finance/code/contributing#committing). In your case you need to capitalize "extend"

Hey sorry @hachiojidev, this was one of my firsts commit where I had an issue with husky + windows.

I changed the commit message, is this good now or should I create a new branch / commit with a new PR?

2021-05-21 02:27 UTC, hachiojidev commented
@ciruz Thanks for updating the commit messages. One more thing, it seems there is a formatting issue. Can you run `yarn format:write` or check and fix the issue.

2021-05-21 06:00 UTC, ciruz commented
@hachiojidev done

2021-06-07 06:01 UTC, hachiojidev requested changes

2021-06-07 06:01 UTC, hachiojidev commented on packages/pancake-uikit/src/widgets/Menu/components/PanelBody.tsx
> +                  item.href === location.pathname || (item.href.length > 1 && location.pathname.startsWith(item.href))
Similar to my comment below `item.href.length > 1` is superfluous.

2021-06-07 06:01 UTC, hachiojidev commented on packages/pancake-uikit/src/widgets/Menu/components/PanelBody.tsx
> +                      (item.href.length > 1 && location.pathname.startsWith(item.href))
>Similar to my comment below `item.href.length > 1` is superfluous.

2021-07-15 01:30 UTC, hachiojidev commented
@ciruz Again, thank you for submitting this. However, I am going to close this for now because we have some big plans upcoming with the menu and this will not be necessary.

2021-07-15 01:30 UTC, closed without merging