feat(bottom nav): Add bottom navigation on mobile
pancakeswap/pancake-toolkit pull request #264
Opened 2021-09-03 16:27 UTC by 0xCorgi

TBD

2021-09-06 09:35 UTC, hachiojidev requested changes
Just rebase to make sure icons are still good.

2021-09-06 09:35 UTC, hachiojidev commented on packages/pancake-uikit/src/components/Svg/Icons/Earn.tsx
> +    <Svg viewBox="0 0 22 20" {...props}>
This should be 24x24.

2021-09-06 09:35 UTC, hachiojidev commented on packages/pancake-uikit/src/components/Svg/Icons/Earn.tsx
> +    <Svg viewBox="0 0 22 20" {...props}>
I added this icon just now. Go ahead and rebase.

2021-09-06 22:59 UTC, hachiojidev commented
@0xCorgi Please make sure to rebase. I see a lot of duplicate commits.

2021-09-07 07:42 UTC, 0xCorgi commented
> @0xCorgi Please make sure to rebase. I see a lot of duplicate commits.

This PR will be a nightmare to rebase. I think it would be best to squash the commit on this one.
I already merge your changes to make sure the icons are still good.
I'll rebase the final PR at the end anyways.

2021-09-07 14:11 UTC, merged