feat(footer navigation): Add Footer component
pancakeswap/pancake-toolkit pull request #268
Opened 2021-09-06 17:02 UTC by 0xCorgi

[Current preview](https://corgi-footer.surge.sh/?path=/story/components-menu-footer--default)

![image](https://user-images.githubusercontent.com/88371449/132247340-d59bf228-2690-4266-8d3a-412dc12660b3.png)

2021-09-08 17:19 UTC, ChefHutch reviewed
Nice work man, spotted two things on mobile on Brave, this button was really unresponsive:
<img width="404" alt="Screenshot 2021-09-08 at 18 15 51" src="https://user-images.githubusercontent.com/79279477/132554960-51a9e8d0-ffff-4a02-8d6b-c51884852a1a.png">

The menu should presumably be centred, and scale as the device gets smaller? Currently it trails off the screen
<img width="486" alt="Screenshot 2021-09-08 at 18 15 22" src="https://user-images.githubusercontent.com/79279477/132555017-c4589bf5-386d-4846-b5b4-dd351f7af4d8.png">

2021-09-08 17:19 UTC, ChefHutch commented on packages/pancake-uikit/src/components/CakePrice/CakePrice.tsx
> +      href="https://exchange.pancakeswap.finance/#/swap?outputCurrency=0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82"
This is the old address - the other one is right 👌

2021-09-08 17:19 UTC, ChefHutch commented on packages/pancake-uikit/src/components/Svg/Icons/Github.tsx
> +    <Svg xmlns="http://www.w3.org/2000/svg" {...props}>
I think we ought to declare the viewbox value here. Not sure we need the xmlns attribute? Goes for the other SVGs too

2021-09-08 17:19 UTC, ChefHutch commented on packages/pancake-uikit/src/widgets/Menu/icons/Farm.tsx
> -const Icon: React.FC<SvgProps> = (props) => {
Awesome to delete all these - can you check they aren't used in the FE somewhere though - some find there way onto one-off cards?

If they are used - move them over to where the regular icons live 👍

2021-09-09 01:30 UTC, hachiojidev requested changes
Nice work. Just fixed the small issues Hutch raised and we are good to go.

2021-09-09 01:30 UTC, hachiojidev commented on packages/pancake-uikit/src/widgets/Menu/Menu.tsx
> +import { noop } from "lodash";
We can remove this.

2021-09-10 14:39 UTC, merged