Fix for yarn format:check following workspaces migration
pancakeswap/pancake-toolkit pull request #5
Opened 2021-03-16 15:41 UTC by ChefHutch

One of out Github workflows is targeting a command within the uikit package, causing an error in CI:

<img width="696" alt="Screenshot 2021-03-16 at 15 39 43" src="https://user-images.githubusercontent.com/79279477/111337274-dd763180-866d-11eb-9216-a6b8b17c580f.png">

This is a potential fix - CDing into the directory before running the check.

2021-03-16 15:43 UTC, ChefHutch commented
<img width="518" alt="Screenshot 2021-03-16 at 15 43 1 ="https://user-images.githubusercontent.com/79279477/111337856-57a6b600-866e-11eb-8f0a-ffb2218f32f7.png">
😄

2021-03-17 01:13 UTC, hachiojidev requested changes

2021-03-17 01:13 UTC, hachiojidev commented on .github/workflows/format.yml
> +        run: cd ./packages/pancake-uikit && yarn format:check
I think in this case we need to standardize the call at top-level. Lets change the top level command from `"format": "lerna run format",` to `"format:check": "lerna run format:check",`

2021-03-17 01:38 UTC, hachiojidev commented
@ChefHutch I created a PR doing the same thing I asked you to do since your day is ending and mine is beginning.
https://github.com/pancakeswap/pancake-toolkit/pull/6

2021-03-17 01:38 UTC, closed without merging

2021-03-17 08:15 UTC, ChefHutch commented
Champ, ty @hachiojidev